services:
  - type: web
    name: reviewchanthat-api
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: AVIATIONSTACK_API_KEY
        scope: run
        value: f03fa98d3d7917445de7afdec55ddb94
      - key: FLASK_ENV
        scope: run
        value: production
      - key: PORT
        scope: run
        value: 10000

  - type: static_site
    name: reviewchanthat-web
    plan: free

    buildCommand: hugo --gc --minify
    publishPath: public

    envVars:
      - key: HUGO_VERSION
        value: "0.163.1"
